import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/nav-bar/Navbar";
import Loader from "@/components/loader/Loader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Navbar isLoggedIn={true} />
        <Loader/>
        {children}
      </body>
    </html>
  );
}
